version: "3"
services:
  node:
    image: "node:latest"
    user: "node"
    working_dir: "/home/node/app"
    volumes:
      - ./:/home/node/app
    ports:
      - 4000:4000
    command: "npm start"
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASS=grand-todo-dev
    links:
      - "neo4j"
    depends_on:
      - "neo4j"

  neo4j:
    container_name: "neo4j"
    image: "neo4j:latest"
    environment:
      - NEO4J_AUTH=neo4j/grand-todo-dev
    volumes:
      - ./data/:/data
    ports:
      - 7687:7687
      - 7474:7474

